name: 'Terraform'

on:
  push:
    branches: [ "main" ]
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check IP
        run: |
          echo "Runner's IP Address:"
          curl https://ifconfig.me
# jobs:
#   terraform:
#     name: 'Terraform'
#     runs-on: ubuntu-latest
#     environment: production
#     env:
#       ARM_CLIENT_ID: ${{ secrets.AZURE_AD_CLIENT_ID }}
#       ARM_CLIENT_SECRET: ${{ secrets.AZURE_AD_CLIENT_SECRET }}
#       ARM_TENANT_ID: ${{ secrets.AZURE_AD_TENANT_ID }}
#       ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION }}
#       TF_VERSION: 1.0

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v3

#       - name: Setup Terraform
#         uses: hashicorp/setup-terraform@v1
#         with:
#           terraform_version: ${{ env.TF_VERSION }}

#       - name: Terraform Init
#         run: terraform init
#         working-directory : prd

#       - name: terraform fmt
#         run: terraform fmt --recursive
#         working-directory : prd
      

#       - name: Terraform Plan
#         run: terraform plan
#         working-directory : prd

#       - name: Terraform Apply
#         run: terraform apply -auto-approve
#         working-directory : prd
                
