name: 'Terraform'

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    environment: production
    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_AD_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_AD_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION }}
      ARM_TENANT_ID: ${{ secrets.AZURE_AD_TENANT_ID }}

    steps:
      - name: Clean up previous Terraform files
        run: rm -rf .terraform

      - name: Initialize Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.1.0
        env:
          TF_CLI_ARGS: "-backend-config=./prd/main.tf"

      - name: Terraform Init
        run: terraform init ./modules

      - name: Terraform Plan
        run: terraform plan -var-file=./modules/vars.tfvars ./modules

      - name: Terraform Apply
        run: terraform apply -auto-approve -var-file=./modules/vars.tfvars ./modules
